services:
  betnacional-multiplas:
    image: renaneunao/betnacional-multiplas:latest
    container_name: betnacional-multiplas
    restart: unless-stopped
    ports:
      - "0.0.0.0:8003:8002"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - betnacional-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  betnacional-net:
    name: betnacional-net
    external: true
